/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ImageQuality: typeof import('./src/components/ImageQuality/index.vue')['default']
    OCRingDialog: typeof import('./src/components/OCRingDialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScanProgress: typeof import('./src/components/ScanProgress/index.vue')['default']
    SettingDialog: typeof import('./src/components/SettingDialog/index.vue')['default']
  }
}
